version: '3'
services:
  mynginx:
    image: nginx
    volumes:
      - "../target/classes//static:/usr/share/nginx/html/static"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      mynet:
        ipv4_address: 172.18.0.2
    ports:
      - "8080:80"

  webnode-1:
    build: ./webnode
    volumes:
      - "/tmp"
      - "../target/webapp-1.0-SNAPSHOT.jar:/app.jar"
      - "/config"
      - "../config/application-prd.1.properties:/config/application-prd.properties"
      - "../config/log4j2.xml:/config/log4j2.xml"
    networks:
      mynet:
        ipv4_address: 172.18.0.3
    ports:
          - "8083:8080"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  webnode-2:
    build: ./webnode
    volumes:
      - "/tmp"
      - "../target/webapp-1.0-SNAPSHOT.jar:/app.jar"
      - "/config"
      - "../config/application-prd.2.properties:/config/application-prd.properties"
      - "../config/log4j2.xml:/config/log4j2.xml"
    networks:
      mynet:
        ipv4_address: 172.18.0.4
    ports:
          - "8084:8080"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  webnode-3:
    build: ./webnode
    volumes:
      - "/tmp"
      - "../target/webapp-1.0-SNAPSHOT.jar:/app.jar"
      - "/config"
      - "../config/application-prd.3.properties:/config/application-prd.properties"
      - "../config/log4j2.xml:/config/log4j2.xml"
    networks:
      mynet:
        ipv4_address: 172.18.0.5
    ports:
          - "8085:8080"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  zookeeper-1:
    image: wurstmeister/zookeeper
    volumes:
      - "./zoo.cfg:/opt/zookeeper-3.4.9/conf/zoo.cfg"
      - "./myid-1:/opt/zookeeper-3.4.9/data/myid"
    networks:
      mynet:
        ipv4_address: 172.18.0.6
#    ports:
#      - "22:22"
  zookeeper-2:
    image: wurstmeister/zookeeper
    volumes:
      - "./zoo.cfg:/opt/zookeeper-3.4.9/conf/zoo.cfg"
      - "./myid-2:/opt/zookeeper-3.4.9/data/myid"
    networks:
      mynet:
        ipv4_address: 172.18.0.7
#    depends_on:
#      - zookeeper-1
  zookeeper-3:
    image: wurstmeister/zookeeper
    volumes:
      - "./zoo.cfg:/opt/zookeeper-3.4.9/conf/zoo.cfg"
      - "./myid-3:/opt/zookeeper-3.4.9/data/myid"
    networks:
      mynet:
        ipv4_address: 172.18.0.8
#    depends_on:
#      - zookeeper-2
#      - zookeeper-1

  kafka-1:
    image: wurstmeister/kafka
    volumes:
      - "./kafka.server.1.properties:/opt/kafka/config/server.properties"
    networks:
          mynet:
            ipv4_address: 172.18.0.9
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 9092:9092
  kafka-2:
      image: wurstmeister/kafka
      volumes:
        - "./kafka.server.2.properties:/opt/kafka/config/server.properties"
      networks:
            mynet:
              ipv4_address: 172.18.0.10
      depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3
  kafka-3:
      image: wurstmeister/kafka
      volumes:
        - "./kafka.server.3.properties:/opt/kafka/config/server.properties"
      networks:
            mynet:
              ipv4_address: 172.18.0.11
      depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3


networks:
  mynet:
    driver: bridge
#    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
#        - gateway: 172.18.0.1